apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-ijhpbmve
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-ijhpbmve:a3d2644580e186fa2b749fd16c6889cae238b797@sha256:f66eb759e923567e7d57b74be83222c45b8f8c5d4d70a46af6fb349fd36ec046
          name: container-image
